---

- hosts: all
  become: true
  tasks: 


  - name: install apache package & php
#   apt: 
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

#    when: ansible_distribution == "Ubuntu"

      
