---

- hosts: all
  become: true
  pre_tasks: 

  
  - name: update repo cache (Ubuntu)
    tags: always
    apt:
#Confirming cache is current to allow apts to run#
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"



  - name: install updates (CentOS)
    dnf:
      update_cache: yes
#Flagging any change reg - false#
    changed_when: false
    when: ansible_distribution == "CentOS"


  - name: service start (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"


  - name: change e-mail address for admin (CentOS)
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "CentOS"
    register: remark

  - name: restart httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: remark.changed



- hosts: all
  become: true
  roles:
    - base 


- hosts: workstations
  become: true
#  tasks: 
  roles:
    - workstations 

      
- hosts: web_servers
  become: true 
#  tasks:
  roles:
    - web_servers


- hosts: db_servers
  become: true
#  tasks:
  roles:
    - db_servers 
  

- hosts: file_servers
  become: true
#  tasks:
  roles:
    - file_servers





