  - name: install apache and php for Ubuntu
    tags: apache,apache2,ubuntu
    package:
#    apt:
      name:
#        - apache2
#        - libapache2-mod-php
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: start & enable apache service
    tags: apache,httpd
    service:
#     name: apache2 
      name: "{{ apache_service }}"
      state: started
      enabled: yes


  - name: change e-mail address for admin (CentOS)
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "CentOS"
#    register: remark
    notify: restart_apache




  - name: copy default html file
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

